###
# 파일명: config/deidentification.yml
# 목적: 구조화 및 비식별화 설정
# 기능: 
#   - "Python의 r'…' 표기는 쓰지 말고, YAML에서는 작은따옴표로 감싸서 정규식 백슬래시는 그대로 적는다"가 정확한 가이드입니다
#   - 병리보고서(execl format) raw/structured/deidentified data 경로 지정
#   - excel에서 병리보고서가 포함된 컬럼이름 지정
#   - 데이터변화이후 각 컬럼의 이름에 접두사 지정
#   - 병리보고서의 여러 section(섹션)을 검색하여 삭제할지 추출할지 지정  
#   - section 중에서 gross_findings(육안소견)과 pathologic_diagnosis(병리진단)을 순서를 나중에 배치한 것은 다른 섹션을 삭제하고 남은 것 중에서 추출하는 것이 구현하기 쉽기 때문
#   - target은 비식별화대상 항목임
# 변경이력
#  - 2025-09-28: 비정형보고서를 먼저 정향화(컬럼화)한후 진행하도록 전략을 수정 (BenKorea)
#  - 2025-09-25: .key 메소드로 비식별화 대상 컬럼명을 리스트로 획득할 수 있도록 수정 (BenKorea)
###

pathology_report:
  # 경로 설정
  paths:
    input_dir: data/raw/pathology_report
    output_dir: data/deidentified/pathology_report
    structured_dir: data/structured/pathology_report  # 1단계 구조화 결과

  # 리포트 컬럼 매핑 설정
  column_mapping:
    report_column_name: pathology_report


  targets:

    # 삭제할 타겟
    title:
      pattern_description: "`조직병리 검사 결과지` 문구"
      regular_expression: '^(조직병리\s*검사\s*결과지)'
      structuralization_policy: remove # [remove|extraction]

    signature:
      pattern_description: "이 결과지는 전자서명법에 의하여 전자서명된 문서입니다."
      regular_expression: '(이\s*결과지는\s*전자서명법에\s*의하여\s*전자서명된\s*문서입니다.)'
      structuralization_policy: remove # [remove|extraction]

    footer:
      pattern_description: "`한국원자력의학원`으로 시작하는 줄과 그 다음 줄"
      regular_expression: '(?:^|\r?\n)(\s*한국원자력의학원[^\r\n]*\r?\n[^\r\n]*\r?\n)'
      structuralization_policy: remove # [remove|extraction]

    page:
      pattern_description: "`줄 전체에 숫자 / 숫자 만 있는 경우"
      regular_expression: '(\s+\d+\s+/\s+\d+\s+)'
      structuralization_policy: remove # [remove|extraction]

    # 추출할 타겟
    icd_code:
      pattern_description: "`상 병 :`로 시작하는 줄에서 나머지"
      regular_expression: '^.*?(?=\s*검 체)(?P<ICDcode>[\s\S]*?)(?=\n\s*◎ 육 안 소 견)'
      structuralization_policy: extraction # [remove|extraction]

    exam:
      pattern_description: "`검 사 :`로 시작하는 줄에서 나머지"
      regular_expression: '\s*검 체[^\n]*\n(?P<exam>[\s\S]*?)(?=\n\s*◎ 육 안 소 견)'
      structuralization_policy: extraction # [remove|extraction]

    specimen:
      pattern_description: "`검 체 :`로 시작하는 줄에서 나머지"
      regular_expression: '\s*검 체[^\n]*\n(?P<specimen>[\s\S]*?)(?=\n\s*◎ 육 안 소 견)'
      structuralization_policy: extraction # [remove|extraction]
    gross_findings:
      pattern_description: "` ◎ 육 안 소 견`으로 시작하는 줄에서 첫번째 ` ◎ 병 리 진 단`으로 시작되는 줄 이전까지 "
      regular_expression: '\s*◎ 육 안 소 견[^\n]*\n(?P<gross_findings>[\s\S]*?)(?=\n\s*◎ 병 리 진 단)'
      structuralization_policy: extraction # [remove|extraction]
         
    pathologic_diagnosis:
      pattern_description: "` ◎ 병 리 진 단`으로 시작하는 줄에서 마지막까지"
      regular_expression: '\s*◎ 병 리 진 단[^\n]*\n(?P<pathologic_diagnosis>[\s\S]*?)(?=\n\s*결과 입력)'
      structuralization_policy: extraction # [remove|extraction]

  # 비식별화 대상들
    printer_id:
      pattern_description: "출력자ID:숫자4~8자리"
      regular_expression: '출력자ID\s*:\s*(?P<printer_id>[0-9]{4,8})'
      structuralization_policy: extraction # [remove|extraction]      
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_numeric # [fpe_numeric|hash]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOOOOOO"

    pgm_id:
      pattern_description: "PGM_ID : 영문숫자8자리"
      regular_expression: 'PGM_ID\s*:\s*(?P<pgm_id>[A-Za-z0-9]{8})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_alphanumeric  # [fpe_alphanumeric|hash]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOOOOOO"

    print_date:
      pattern_description: "출력일 : yyyy-mm-dd"
      regular_expression: '출력일\s*:\s*(?P<print_date>\d{4}-\d{2}-\d{2})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: year_to_january_first # [month_to_first_day|year_to_january_first]
      anonymization_policy: masking # [masking]
      anonymization_value: "yyyy-mm-dd"

    pathology_id:
      pattern_description: "병리번호: 영문숫자3or4개-숫자4or5개 "
      regular_expression: '병리번호\s*:\s*(?P<pathology_id>[A-Za-z0-9]{3,4}-[0-9]{4,5})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_alphanumeric  # [fpe_alphanumeric|hash]
      anonymization_policy: serial_number # [serial_number|masking]
      anonymization_value: "OOO-OOOOO"

    receipt_date:
      pattern_description: "접 수 일: yyyy-mm-dd"
      regular_expression: '접 수 일\s*:\s*(?P<receipt_date>\d{4}-\d{2}-\d{2})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: year_to_january_first # [month_to_first_day|year_to_january_first]
      anonymization_policy: masking # [masking]
      anonymization_value: "yyyy-mm-dd"

    patient_name:
      pattern_description: "환 자 명: 한글문자열"
      regular_expression: '환 자 명\s*:\s*(?P<pname>[가-힣]+)'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    referring_physician:
      pattern_description: "의뢰의사: 한글문자열"
      regular_expression: '의뢰의사\s*:\s*(?P<ref_physician>[가-힣]+)'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    patient_id:
      pattern_description: "등록번호: 숫자8개"
      regular_expression: '등록번호\s*:\s*(?P<pid>[0-9]{8})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_numeric  # [fpe_numeric|hash]
      anonymization_policy: serial_number # [serial_number|masking]
      anonymization_value: "OOOOOOOO"

    referring_department:
      pattern_description: "의 뢰 과: 한글문자열"
      regular_expression: '의 뢰 과\s*:\s*(?P<ref_department>[가-힣]+)'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOOOOOO"

    sex:
      pattern_description: "성별/나이: F|M"
      regular_expression: '성별/나이\s*:\s*(?P<sex>[FM])'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "O"

    age:
      pattern_description: "성별/나이: F or M / 숫자3개이하" 
      regular_expression: '성별/나이\s*:\s*[FMO]\s*/\s*(?P<age>\d{1,3})' # sex가 가명화가 먼저 되기에 O 필요
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: age_to_5year_group # [age_to_5year_group|age_to_10year_group]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOO"

    ward:
      pattern_description: "병동/병실: 영문1숫자1 / 숫자2"
      regular_expression: '병동/병실\s*:\s*(?P<ward>[A-Z][0-9]+)\s*/\s*[0-9]{2}'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OO"

    room:
      pattern_description: "병동/병실: 영문1숫자1 / 숫자2"
      regular_expression: '병동/병실\s*:\s*[A-Z0-9]{2}\s*/\s*(?P<room>[0-9]{2})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OO"  

    patient_type:
      pattern_description: "공백으로 둘러싸인 외래 또는 입원 단어"
      regular_expression: '\s+(?P<patient_type>외래|입원)\s+'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OO"

    result_date:
      pattern_description: "결 과 일: yyyy-mm-dd"
      regular_expression: '결 과 일\s*:\s*(?P<result_date>\d{4}-\d{2}-\d{2})'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: year_to_january_first # [month_to_first_day|year_to_january_first]
      anonymization_policy: masking # [masking]
      anonymization_value: "yyyy-mm-dd"

    attending_physician:
      pattern_description: "담당의사 : 한글문자열"
      regular_expression: '담당의사\s*:\s*(?P<attending_physician>[가-힣]+)'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    gross_id:
      pattern_description: "영문숫자4자리-숫자4자리 육안사진촬영 (예: SA16-3492   육안사진촬영)"
      regular_expression: '(?P<gross_id>[A-Za-z0-9]{4}-[A-Za-z0-9]{4})\s*육안사진촬영'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_alphanumeric  # [fpe_alphanumeric|hash]
      anonymization_policy: serial_number # [serial_number|masking]
      anonymization_value: "OOOO-OOOO" 

    result_inputter:
      pattern_description: "결과 입력 : 한글이름 (예: 결과 입력 : 홍길동 )"
      regular_expression: '결과 입력\s*:\s*(?P<result_inputter>[가-힣]+)'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    pathologists:
      pattern_description: "병리전문의 : 한글이름/한글이름(예: 병리전문의 : 홍길동/이순신 )"
      regular_expression: '병리전문의\s*:\s*(?P<pathologists>[가-힣/]+)'
      structuralization_policy: extraction # [remove|extraction]
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO/OOOO"
