###
# 파일명: config/deidentification.yml
# 목적: 구조화 및 비식별화 설정
# 기능: 
#   - "Python의 r'…' 표기는 쓰지 말고, YAML에서는 작은따옴표로 감싸서 정규식 백슬래시는 그대로 적는다"가 정확한 가이드입니다
#   - 병리보고서(execl format) raw/structured/deidentified data 경로 지정
#   - excel에서 병리보고서가 포함된 컬럼이름 지정
# 변경이력
#  - 2025-09-28: 비정형보고서를 먼저 정향화(컬럼화)한후 진행하도록 전략을 수정 (BenKorea)
#  - 2025-09-25: .key 메소드로 비식별화 대상 컬럼명을 리스트로 획득할 수 있도록 수정 (BenKorea)
###

pathology_report:
  # 경로 설정
  paths:
    input_dir: data/raw/pathology_report
    output_dir: data/deidentified/pathology_report
    structured_dir: data/structured/pathology_report  # 1단계 구조화 결과

  # 기존 컬럼 매핑 (targets와 같은 설정으로 비식별화가 필요한 컬럼들을 매칭)
  existing_column_mapping:
    patient_id: patient_id
    result_date: result_date
    pathology_id: pathology_id
    report_column: pathology_report # 병리보고서가 포함된 컬럼명

  # 보고서내 중복된 부분과 컬럼으로 추출할 필요없이 삭제만 하면 되는 것들
  non_targets:
    title:
      pattern_description: "`조직병리 검사 결과지` 문구"
      regular_expression: '^(?P<title>조직병리\s*검사\s*결과지)'

    signature:
      pattern_description: "이 결과지는 전자서명법에 의하여 전자서명된 문서입니다."
      regular_expression: '(?P<signature>이\s*결과지는\s*전자서명법에\s*의하여\s*전자서명된\s*문서입니다.)'

    duplicated_block:
      pattern_description: "중복되는 블록 (예: '한국원자력의학원' 부터 '검 체 :' 까지)"
      regular_expression: '(?P<duplicated_block>한국원자력의학원[\s\S]*?검 체\s*:[^\n]*\n)'
    
    footer:
      pattern_description: "`한국원자력의학원`으로 시작하는 줄과 그 다음 줄"
      regular_expression: '(?P<footer>(?:^|\r?\n)\s*한국원자력의학원[^\r\n]*\r?\n[^\r\n]*\r?\n)'

    page_number:
      pattern_description: "' 숫자 / 숫자 문장끝' 만 추출"
      regular_expression: '\s+(?P<page_number>\d{1}\s*/\s*\d{1})\s*$'


  targets:
    icd_code:
      pattern_description: "`상 병 :`로 시작하는 줄에서 나머지"
      regular_expression: '\s*상 병\s*:\s*(?P<icd_code>.*)$'

    exam:
      pattern_description: "`검 사 :`로 시작하는 줄에서 나머지"
      regular_expression: '^\s*검 사\s*:\s*(?P<exam>.*)$'

    specimen:
      pattern_description: "`검 체 :`로 시작하고 첫번째 줄바꿈까지 공백 또는 그안의 내용"
      regular_expression: '^\s*검 체\s*:\s*(?P<specimen>[^\r\n]*)$'     

    gross_pathologist:      # 비식별화 대상이지만 gross_findings에 포함되기에 삭제 전에 미리 추출
      pattern_description: "담당의사 : 한글문자열"
      regular_expression: '담당의사\s*:\s*(?P<attending_physician>[가-힣]+)'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO" 

    gross_findings:
      pattern_description: "` ◎ 육 안 소 견`으로 시작하는 줄에서 첫번째 ` ◎ 병 리 진 단`으로 시작되는 줄 이전까지 "
      regular_expression: '\s*◎ 육 안 소 견[^\n]*\n(?P<gross_findings>[\s\S]*?)(?=\n\s*◎ 병 리 진 단)'

    photo_id:              # 비식별화 대상이지만 pathologic_diagnosis에 포함되기에 삭제 전에 미리 추출
      pattern_description: "영문숫자4자리-숫자4자리 육안사진촬영 (예: SA16-3492   육안사진촬영)"
      regular_expression: '(?P<photo_id>[A-Za-z0-9]{4}-[A-Za-z0-9]{4})\s*육안사진촬영'
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_alphanumeric  # [fpe_alphanumeric|hash]
      anonymization_policy: serial_number # [serial_number|masking]
      anonymization_value: "OOOO-OOOO" 

    pathologic_diagnosis:
      pattern_description: "` ◎ 병 리 진 단`으로 시작하는 줄에서 마지막까지"
      regular_expression: '\s*◎ 병 리 진 단[^\n]*\n(?P<pathologic_diagnosis>[\s\S]*?)(?=\n\s*결과 입력)'

  

  # 비식별화 targets
    printer_id:
      pattern_description: "출력자ID:숫자4~8자리"
      regular_expression: '출력자ID\s*:\s*(?P<printer_id>[0-9]{4,8})'   
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_numeric # [fpe_numeric|hash]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOOOOOO"  

    pgm_id:
      pattern_description: "PGM_ID : 영문숫자8자리"
      regular_expression: 'PGM_ID\s*:\s*(?P<pgm_id>[A-Za-z0-9]{8})'
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_alphanumeric  # [fpe_alphanumeric|hash]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOOOOOO"

    print_date:
      pattern_description: "출력일 : yyyy-mm-dd"
      regular_expression: '출력일\s*:\s*(?P<print_date>\d{4}-\d{2}-\d{2})'
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: year_to_january_first # [month_to_first_day|year_to_january_first]
      anonymization_policy: masking # [masking]
      anonymization_value: "yyyy-mm-dd"

    pathology_id:
      pattern_description: "병리번호: 영문숫자3or4개-숫자4or5개 "
      regular_expression: '병리번호\s*:\s*(?P<pathology_id>[A-Za-z0-9]{3,4}-[0-9]{4,5})'
      deidentification_policy: anonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_alphanumeric  # [fpe_alphanumeric|hash]
      anonymization_policy: serial_number # [serial_number|masking]
      anonymization_value: "OOO-OOOOO"

    receipt_date:
      pattern_description: "접 수 일: yyyy-mm-dd"
      regular_expression: '접 수 일\s*:\s*(?P<receipt_date>\d{4}-\d{2}-\d{2})'
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: year_to_january_first # [month_to_first_day|year_to_january_first]
      anonymization_policy: masking # [masking]
      anonymization_value: "yyyy-mm-dd"

    patient_name:
      pattern_description: "환 자 명: 한글문자열"
      regular_expression: '환 자 명\s*:\s*(?P<pname>[가-힣]+)'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    referring_physician:
      pattern_description: "의뢰의사: 한글문자열"
      regular_expression: '의뢰의사\s*:\s*(?P<ref_physician>[가-힣]+)'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    patient_id:
      pattern_description: "등록번호: 숫자8개"
      regular_expression: '등록번호\s*:\s*(?P<pid>[0-9]{8})'
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: fpe_numeric  # [fpe_numeric|hash]
      anonymization_policy: serial_number # [serial_number|masking]
      anonymization_value: "OOOOOOOO"

    referring_department:
      pattern_description: "의 뢰 과: 한글문자열"
      regular_expression: '의 뢰 과\s*:\s*(?P<ref_department>[가-힣]+)'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOOOOOO"

    sex:
      pattern_description: "성별/나이: F|M "
      regular_expression: '성별/나이\s*:\s*(?P<sex>[FM])'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "O"

    age:
      pattern_description: "문장의시작 / 숫자3개이하 " # sex를 추출 후 삭제하면 조건이 이렇게 됨
      regular_expression: '^\s*/\s*(?P<age>\d{1,3})\s*' # 문장의 시작에서 숫자 3개 이하를 추출
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: age_to_5year_group # [age_to_5year_group|age_to_10year_group]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOO"

    ward:
      pattern_description: "병동/병실: 영문1숫자1" 
      regular_expression: '병동/병실\s*:\s*(?P<ward>[A-Z][0-9]+)\s*'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OO"

    room:
      pattern_description: "문장의시작 / 숫자2개이하 " # 병동을 추출 후 삭제하면 조건이 이렇게 됨
      regular_expression: '^\s*/\s*(?P<room>\d{1,2})\s*' # 문장의 시작에서 숫자 2개 이하를 추출
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OO"  

    patient_type:
      pattern_description: "외래/입원:+공백+[외래|입원]"
      regular_expression: '\s*외래/입원:\s*(?P<patient_type>외래|입원)\s+'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OO"

    result_date:
      pattern_description: "결 과 일: yyyy-mm-dd"
      regular_expression: '결 과 일\s*:\s*(?P<result_date>\d{4}-\d{2}-\d{2})'
      deidentification_policy: pseudonymization # [pseudonymization|anonymization|no_apply]
      pseudonymization_policy: year_to_january_first # [month_to_first_day|year_to_january_first]
      anonymization_policy: masking # [masking]
      anonymization_value: "yyyy-mm-dd" 



    result_inputter:
      pattern_description: "결과 입력 : 한글이름 (예: 결과 입력 : 홍길동 )"
      regular_expression: '결과 입력\s*:\s*(?P<result_inputter>[가-힣]+)'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    diagnosis_pathologist_1:
      pattern_description: "병리전문의 : 한글이름/(예: 병리전문의 : 홍길동)"
      regular_expression: '병리전문의\s*:\s*(?P<diagnosis_pathologist_1>[가-힣]+)(?:/|\s|$)'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

    diagnosis_pathologist_2:
      pattern_description: "한글이름" # pathologist_1을 삭제하고 남은 한글이름
      regular_expression: '(?P<diagnosis_pathologist_2>[가-힣]+)\s*$'
      deidentification_policy: anonymization # [anonymization|no_apply]
      pseudonymization_policy: not_supported  # [not_supported]
      anonymization_policy: masking # [masking]
      anonymization_value: "OOOO"

   