# config/pseudonymization.yml
# “Python의 r'…' 표기는 쓰지 말고, YAML에서는 작은따옴표로 감싸서 정규식 백슬래시는 그대로 적는다”가 정확한 가이드입니다
# last-modified: 2025-08-27

pathology_report:
  input_dir: data/raw/pathology_report
  output_dir: data/pseudonymized/pathology_report

  printer_id:
    pattern_description: "출력자:아라비아숫자 4~8자리 공백"
    regular_expression: '(?<!\S)출력자ID\s*[:：]?\s*(?P<printer_id>[0-9]{4,8})(?!\S)'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    anonymization_value: "OOOO"

  PGM_ID:
    pattern_description: "PGM_ID 공백 : 공백 `숫자와 문자가 혼합된 8자리문자열` 공백"
    regular_expression: '(?<!\S)PGM_ID\s*[:：]?\s*(?P<pgm_id>[A-Za-z0-9]{8})(?!\S)'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    anonymization_value: "OOOOOOOO"

  print_date:
    pattern_description: "출력일 : 공백 yyyy-mm-dd 공백"
    regular_expression: '(?<!\S)출력일\s*[:：]?\s*(?P<print_date>\d{4}-\d{2}-\d{2})(?!\S)'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    pseudonymization_values: year_to_january_first # month_to_first_day/year_to_january_first
    anonymization_value: "yyyy-mm-dd"

  pathology_id:
    pattern_description: "병리번호: 공백 문자1개숫자2개-아라비아숫자5개 공백"
    regular_expression: '(?<!\S)병리번호\s*[:：]?\s*(?P<pathology_id>[A-Z]{1,2}[0-9]{2,5}-[0-9]{3,5})(?!\S)'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    anonymization_value: "OOO-OOOOO"

  receipt_date:
    pattern_description: "접 수 일: 공백 yyyy-mm-dd 공백"
    regular_expression: '(?<!\S)접 수 일\s*[:：]?\s*(?P<receipt_date>\d{4}-\d{2}-\d{2})(?!\S)'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    pseudonymization_values: year_to_january_first # month_to_first_day/year_to_january_first
    anonymization_value: "yyyy-mm-dd"

  patient_name:
    pattern_description: "환 자 명: 공백 문자열 공백"
    regular_expression: '(?<!\S)환 자 명\s*[:：]?\s*(?P<pname>[가-힣]+)(?!\S)'
    deidentification_policy: anonymization # anonymization/no_apply  
    anonymization_value: "OOO"

  referring_physician:
    pattern_description: "의뢰의사: 공백 문자열 공백"
    regular_expression: '(?<!\S)의뢰의사\s*[:：]?\s*(?P<ref_physician>[가-힣]+)(?!\S)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOO"

  patient_id:
    pattern_description: "등록번호 공백 아라비아숫자8개 공백"
    regular_expression: '(?<!\S)등록번호\s*[:：]?\s*(?P<pid>[0-9]{8})(?!\S)'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    anonymization_value: "OOOOOOOO"

  referring_department:
    pattern_description: "의 뢰 과: 공백 문자열 공백"
    regular_expression: '(?<!\S)의 뢰 과\s*[:：]?\s*(?P<ref_department>[가-힣]+)(?!\S)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOOOOOOO"

  sex:
    pattern_description: "성별/나이: 공백 문자열1개  공백"
    regular_expression: '성별/나이\s*[:：]?\s*(?P<sex>[FM여남])\s*/\s*(?P<age>\d+)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "O"

  age:
    pattern_description: "성별/나이: 공백 문자열1개  공백 / 공백 숫자여러개 공백"
    regular_expression: '성별/나이\s*[:：]?\s*[FM여남O]\s*/\s*(?P<age>\d{1,3})'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    pseudonymization_values: age_to_5year_group # age_to_5year_group/age_to_10year_group
    anonymization_value: "OOO"  

  ward_room:
    pattern_description: "병동/병실: 공백 문자열 공백 / 공백 문자열 공백"
    regular_expression: '병동/병실\s*[:：]?\s*(?P<ward>[가-힣A-Za-z0-9]+)\s*/\s*(?P<room>[A-Za-z0-9]+)(?!\S)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOO/OOO"

  out_inpatient:
    pattern_description: "외래/입원: 공백 (입원|외래) 공백"
    regular_expression: '외래/입원:\s*(?P<oi>입원|외래)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OO"

  result_date:
    pattern_description: "결 과 일: 공백 yyyy-mm-dd 공백"
    regular_expression: '(?<!\S)결 과 일\s*[:：]?\s*(?P<result_date>\d{4}-\d{2}-\d{2})(?!\S)'
    deidentification_policy: anonymization # pseudonymization/anonymization/no_apply
    pseudonymization_values: year_to_january_first # month_to_first_day/year_to_january_first
    anonymization_value: "yyyy-mm-dd"

  attending_physician:
    pattern_description: "담당의사 : 공백 문자열 공백 (':' 앞에 반드시 공백)"
    regular_expression: '(?<!\S)담당의사\s+[:：]\s*(?P<attending_physician>[가-힣]+)(?!\S)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOO"

  phone_number:
    pattern_description: "검사실 : 공백 전화번호(지역번호/국번/번호, 또는 3-4/2-4/4-4 등 다양한 패턴)"
    regular_expression: '(?<!\S)검사실\s*[:：]?\s*(?P<phone_number>(0[0-9]{1,2}-[0-9]{3,4}-[0-9]{4}|[0-9]{2,4}-[0-9]{3,4}))'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOO-OOOO"    

  gross_id:
    pattern_description: "문자2~4+숫자2~4-숫자4자리 뒤에 육안사진촬영 한글 포함 (예: SA16-3492   육안사진촬영)"
    regular_expression: '(?P<gross_id>[A-Za-z]{2,4}[0-9]{2,4}-[0-9]{4})\s*육안사진촬영'
    deidentification_policy: pseudonymization # pseudonymization/anonymization/no_apply
    anonymization_value: "OOOO-OOOO" 

  result_inputter:
    pattern_description: "결과 입력 : 한글 이름 1개 (예: 결과 입력 : 홍길동 )"
    regular_expression: '(?<!\S)결과 입력\s*[:：]?\s*(?P<result_inputter>[가-힣]+)(?!\S)'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOO"

  pathologists:
    pattern_description: "병리전문의 : 한글이름/한글이름(예: 병리전문의 : 홍길동/이순신 )"
    regular_expression: '병리전문의\s*[:：]?\s*(?P<pathologists>[가-힣/\s]+)$'
    deidentification_policy: anonymization # anonymization/no_apply
    anonymization_value: "OOO/OOO"